# Generated by Django 2.2.4 on 2019-08-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('aisle_id', models.ManyToManyField(related_name='aisles', to='shop_it.Aisle')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('section_id', models.ManyToManyField(related_name='store_sections', to='shop_it.Section')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('section_order_preference', models.CharField(default='Produce-First', max_length=225)),
                ('shopping_list', models.ManyToManyField(related_name='shopping_lists', to='shop_it.Product')),
                ('store_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_it.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_third', models.CharField(default='Front-Third', max_length=225)),
                ('product_id', models.ManyToManyField(related_name='products', to='shop_it.Product')),
            ],
        ),
        migrations.AddField(
            model_name='aisle',
            name='shelf_id',
            field=models.ManyToManyField(related_name='shelves', to='shop_it.Shelf'),
        ),
    ]
