# Generated by Django 2.2.4 on 2019-08-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisle',
            name='shelf_id',
            field=models.ManyToManyField(blank=True, related_name='shelves', to='shop_it.Shelf'),
        ),
    ]
